name: Build Inviwo

on: 
  push:
  workflow_dispatch:
  workflow_call:
    inputs:
      ext_modules_repo:
        description: "Repositories for external modules"
        required: false
        type: string
      ext_module_name:
        description: "Name of external module to build and store as artifact"
        required: false
        type: string
      

env:
  BUILD_TYPE: Release
  VCPKG_BINARY_SOURCES: 'clear;nuget,GitHub,readwrite'         # recognized by vcpkg
  # QT_DEBUG_PLUGINS: 1                                        # print qt plugin debug info


jobs:
  build:
    strategy:
      matrix:
        os: [windows-latest, macos-latest, ubuntu-20.04]
        bamodule: ['build/modules/${{ inputs.ext_module_name }}']
        include:
          - os: 'windows-latest'
            triplet: 'x64-windows'
            mono: ''
            cmake: '--preset msvc-dev-vcpkg -DIVW_MODULE_HDF5=ON -DIVW_DOXYGEN_PROJECT=ON 
                    -DIVW_DOXYGEN_LATEX_PATH="C:/tools/TinyTeX/bin/win32/pdflatex.exe"'
            targets: 'ALL_BUILD DOXY-Inviwo DOXY-Python package'
            installer: 'inviwo-installer-win'
            artifact: 'build/inviwo-v*.exe'
            builddir: 'ext-module-win'
            balib: '/build/bin/Release/inviwo-module-${{ inputs.ext_module_name }}.dll'
          - os: 'macos-latest'
            triplet: 'x64-osx'
            mono: 'mono'
            cmake: '--preset ninja-dev-vcpkg -DIVW_MODULE_HDF5=OFF'
            targets: 'all package'
            installer: 'inviwo-installer-macos'
            artifact: 'build/Inviwo-v*.dmg'
            baname: 'ext-module-macos'
            balib: 'build/lib/libinviwo-module-${{ inputs.ext_module_name }}.so'
          - os: 'ubuntu-20.04'
            triplet: 'x64-linux'
            mono: 'mono'
            # Disable benchmark for now due to error: 
            # memcpy’ is not a member of ‘std’; did you mean ‘wmemcpy’
            cmake: '--preset ninja-dev-vcpkg -DIVW_USE_SIGAR=OFF -DIVW_MODULE_HDF5=OFF -DIVW_TEST_BENCHMARKS=OFF' 
            targets: 'all package'
            installer: 'inviwo-installer-ubuntu'
            artifact: 'build/inviwo-v*.zip'
            baname: 'ext-module-ubuntu'
            balib: 'build/lib/libinviwo-module-${{ inputs.ext_module_name }}.so'
      fail-fast: false
      
    runs-on: ${{ matrix.os }}
    timeout-minutes: 360
    
    steps:
    - name: Create external modules folder
      run: mkdir ${{ github.workspace }}/external_modules

    - name: Clone External Module
      if: ${{ ! inputs.ext_modules_repo == 0 }}
      uses: actions/checkout@v2
      with:
        repository: ${{ inputs.ext_modules_repo }}
        path: ${{ github.workspace}}/external_modules/module
        submodules: recursive


    - name: Chocolatey Install 
      if: runner.os == 'Windows'
      shell: bash
      run: |
        choco install doxygen.install 
        choco install nsis
        choco install tinytex
        GP=`cygpath -u $GITHUB_PATH` 
        
        echo "/c/Program Files/doxygen/bin" >> $GP
        echo "/c/Program Files (x86)/NSIS" >> $GP
        echo "/c/tools/TinyTeX/bin/win32" >> $GP

    #- name: Setup tmate session
    #  uses: mxschmitt/action-tmate@v3
    #  timeout-minutes: 60

    - name: Setup Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.10'
        architecture: 'x64'
    
    - name: Install Python Modules 
      shell: bash
      run: pip3 install numpy Sphinx sphinx-rtd-theme recommonmark
    
    - name: Clone VCPKG
      uses: actions/checkout@v2
      with:
        repository: 'microsoft/vcpkg'
        path: 'vcpkg' # The cmake vcpkg present expects vcpkg to be next to the inviwo source folder
    
    # Cache built dependencies for faster subsequent builds
    # TODO: change back xeTaiz -> inviwo, NUGET_KEY -> GITHUB_SECRET
    - name: 'Setup NuGet Credentials'
      shell: bash
      run: >
        ${{ matrix.mono }} `vcpkg fetch nuget | tail -n 1`
        sources add
        -source "https://nuget.pkg.github.com/xeTaiz/index.json"
        -storepasswordincleartext
        -name "GitHub"
        -username "xeTaiz"
        -password "${{ secrets.GITHUB_TOKEN}}"

    - name: Apt Install, switch to gcc-11
      shell: bash
      if: runner.os == 'Linux'
      run: |
        sudo apt install libxinerama-dev libxcursor-dev xorg-dev libglu1-mesa-dev libglew-dev ninja-build doxygen-latex
        sudo apt install gcc-11 g++-11
        sudo update-alternatives --install /usr/bin/gcc gcc /usr/bin/gcc-11 110 --slave /usr/bin/g++ g++ /usr/bin/g++-11 --slave /usr/bin/gcov gcov /usr/bin/gcov-11
        sudo update-alternatives --set gcc /usr/bin/gcc-11
  
    - name: Brew Install
      shell: bash
      if: runner.os == 'macOS'
      run: |
        brew install ninja 

    - name: Install Qt
      uses: jurplel/install-qt-action@v2
      with:
        version: 6.2.3
        dir: ${{ github.workspace }}
        modules: 'qt5compat'
    
    # TODO: Replace to use official inviwo/inviwo repo
    - name: Clone Inviwo
      uses: actions/checkout@v2
      with: 
        repository: 'xeTaiz/inviwo-marketplace'
        ref: updated
        path: inviwo
        submodules: recursive

    - name: Fetch Inviwo SHA
      working-directory: inviwo
      id: ivw-ref
      run: echo "::set-output name=sha::$(git log -1 '--format=format:%H')"

    - name: Cache Build Directory
      uses: actions/cache@v3
      with:
        path: build
        key: ${{ matrix.os }}-${{ steps.ivw-ref.outputs.sha }}
        
    - name: Configure CMake
      shell: bash
      run: >
        cmake -S inviwo -B build
        -DVCPKG_TARGET_TRIPLET='${{ matrix.triplet }}'
        -DCMAKE_BUILD_TYPE=${{ env.BUILD_TYPE }}
        -DIVW_EXTERNAL_MODULES="${{ github.workspace }}/external_modules"
        ${{ matrix.cmake }}

    - name: Setup C++ Log matchers
      uses: Trass3r/setup-cpp@v1

    - name: Build
      timeout-minutes: 360
      shell: bash
      run: cmake --build build --config ${{ env.BUILD_TYPE }} --parallel --target ${{ matrix.targets }}

    - name: Upload Build Dir Artifact
      if: ${{ ! inputs.ext_modules_repo == 0 }}
      uses: actions/upload-artifact@v3
      with:
        name: ${{ matrix.baname }}
        path: |
          ${{ matrix.balib }}
          ${{ matrix.bamodule }}

    - name: Upload installer
      uses: actions/upload-artifact@v2
      with:
        name: ${{ matrix.installer }}
        path: ${{ matrix.artifact }}

    - name: Upload doxygen
      if: runner.os == 'Windows'
      uses: actions/upload-artifact@v2
      with:
        name: inviwo-cpp-api
        path: build/docs/inviwo/html/*

    - name: Upload shpinx
      if: runner.os == 'Windows'
      uses: actions/upload-artifact@v2
      with:
        name: inviwo-python-api
        path: build/docs/python-api/*
